import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container w-4/5 flex-col m-auto px-10 justify-between min-h-screen" >
          <Navbar />
          {children}
          <Footer />
        </div> 
      </body>
    </html>
  );
}
